### ISSUE TITLE
xc7a50t_test database does not contain the part xc7a35tftg256-1

### ISSUE THREAD

**Issue by hansfbaier** [SymbiFlow/symbiflow-arch-defs#2368]
It looks like the mentioned part is already supported by prjxray:
prjxray/settings/resources.yaml contains it:
```yaml
xc7a35tfgg484-2L: *id032
xc7a35tfgg484-3: *id032
xc7a35tftg256-1:
  pins: &id033
    0: N13
    1: K12
    2: F15
    3: K5
```
but the downloadable database for symbiflow does not contain this footprint variant.
What could I do to add this part to the database?
